### ISSUE TITLE
Add a parameter to urls for availabilities and shifts

### ISSUE THREAD

**Issue by leebianca** [codebase-berkeley/moffitt-scheduler#34]
Each user should have their own availabilities and shifts rendered when they go onto "/calendar". For example, SLE 1's availabilities should be rendered on "localhost:3000/calendar/1" and SLE 2's availabilities should be rendered on "localhost:3000/calendar/2". This tutorial should be helpful: [https://scotch.io/courses/using-react-router-4/route-params#:~:text=This%20is%20easy%20to%20do,actual%20value%20in%20the%20URL.](url).

**Comment by bdeleonardis1** [comment]
@stephaniexiao just do the availability calendar for this one, you don't have to do it for /staticcalendar because we're not actually pulling staticcalendar from the database
