### ISSUE TITLE
Create multiple calendars for each location on Open Shifts, Availability, Your Shifts

### ISSUE THREAD

**Issue by kerryhuang1** [codebase-berkeley/moffitt-scheduler#62]
Create different calendars for each location (Main, Moffitt 3rd floor, Moffitt 4th floor): 

- **Open Shifts**
Have a different calendar for each location since hours may overlap. Pull location from backend accordingly. Have a slider/button/something to toggle calendar views.

-  **Availability**
If an SLE is trained for >1 location, nothing on the Availability display (or in the database) currently keeps track of the location the SLE is available for. 
_ex: SLE can be trained for Main and Moffitt 3rd and selects 3PM-6PM on Availability but actually wants 3-4 at Main and 4-6 at Moffitt 3rd._  

- **Your Shifts**
Color coding works since SLE's can't be at two places at once, but this will look bad if the other two calendars can toggle different calendar views based on location. Mostly just for consistency. (NOT AS IMPORTANT AS OTHER TWO)

**Comment by bdeleonardis1** [comment]
I don't think we need this for the availability calendar because what times you are available doesn't depend on the location. It's up to our application not to schedule people for shifts they are unable to cover.
