### ISSUE TITLE
Pull employees from backend rather than hardcode

### ISSUE THREAD

**Issue by bdeleonardis1** [codebase-berkeley/moffitt-scheduler#63]
Right now the employees page is all hardcoded still. Let's pull it from the backend instead.

**Comment by sahilthakur3029** [comment]
Additionally:
1. Split the moffitt training level column to moffitt 3rd and 4th
2. Fix the add employee box to actually work and split moffitt into 3rd and 4th. So you shouldn’t need to modify the database manually but you can if you want
3. Nancy will need to be able to change the training levels eventually but we’ll do that in the future
4. Display what the training level is for each of the three different locations
