### ISSUE TITLE
Pending supervisor and request history not displaying shifts

### ISSUE THREAD

**Issue by stephaniexiao** [codebase-berkeley/moffitt-scheduler#82]
Pending Supervisor and Request History pages have endpoints created in backend file, but shifts are not displaying in frontend. Also, move formatting in /requesthistory outside endpoint so you can access the same formatting for all three tabs (Pending Coverage, Pending Supervisor, Request History) in coverrequests.js

**Comment by bdeleonardis1** [comment]
Closing this for now, I think it's just a problem with Stephanie's sample data. Will reopen if the problem persists.
